---
- name: Patching of RHEL systems
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - debug:
        msg: "Host IP: {{ host_ip }}"
      
      
      
#     - name: add host to selectIP group
#       add_host:
#         name: "{{ host_ip }}"
#         groups: selectIP
# - hosts: selectIP

  
#   tasks:    
#     - name:
#       fail:
#         msg: "Virtual Machine does not have RHEL OS"
#       when: var=hostvars[inventory_hostname].ansible_distribution == "RedHat"
#     - name: update the packages
#       yum:
#         name: '*'
#         state: latest


   
