
---
- name: Add to inventory
  hosts: localhost
  connection: local
  tasks:
     - name: Add the host to the inventory
       tower_host:
         name: "{{ item }}"
         inventory: Demo Inventory
         state: present
         tower_host: {{ TOWER_HOST }}
         tower_username: {{ TOWER_USERNAME }}
         tower_password: {{ TOWER_PASSWORD }}
         tower_verify_ssl: no

      
