
---
- name: Add to inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Ansible Hostname
      debug:
        var: ANSIBLE_HOSTNAME
    - name: Ansible Username
      debug:
        var: ANSIBLE_USERNAME
    - name: Ansible Password
      debug:
        var: ANSIBLE_PASSWORD
#     - name: Add the host to the inventory
#       tower_host:
#         name: "{{ item }}"
#         inventory: "AWS Instance Temp Inventory"
#         state: present
#         tower_host: '103.127.28.115'
#         tower_username: 'inventory_user'
#         tower_password: 'pr0dev@ns987'
#         tower_verify_ssl: no

      
