---
- name: Patching of CentOS/Debian systems
  hosts: localhost
  tasks:
    - name: add host to selectIP group
      add_host:
        groups: selectedIP
        name: "{{ host_ip }}"
    - debug:
        msg: "Host IP: {{ host_ip }}"
        
- hosts: selectedIP
  connection: ssh
  gather_facts: yes
  become: true
  become_method: sudo
  
  tasks: 
    - name: Check  if VM is RHEL machine
      fail:
        msg: " The Machine is neither CentOS or Debian based VM "
      when: ansible_distribution != "CentOS" or ansible_distribution != 'Debian'
    - name: patching for CentOS machine
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == "CentOS"
    - name: patching for Debian machine 
      apt:
        name: '*'
        state: latest
      when: ansible_distribution == "Debian"



   
