---
- name: Patching of CentOS/Debian systems
  hosts: localhost
  tasks:
    - name: add host to selectIP group
      add_host:
        groups: selectIP
        name: "{{ host_ip }}"
    - debug:
        msg: "Host IP: {{ host_ip }}"
        
- hosts: selectIP
  connection: ssh
  gather_facts: yes
  become: true
  become_method: sudo
  
  tasks:    
    - name: Check  if VM is RHEL machine
      vars:
        os: hostvars[inventory_hostname]['ansible_distribution'] 
    - name: check os
      debug:
        var: os
       
#     - name: Check if machine has RedHat Subscription
#       shell:
#         cmd: subscription-manager list | awk '/Status:/ {print $2}'
#       register: status
#     - name: Fail if subscription is not available 
#       fail:
#         msg: " The Virtual Machine does not have RedHat Subscription. Get RedHat Subscription before proceeding "
#       when: status != "Subscribed"
#     - name: update the packages
#       yum:
#         name: '*'
#         state: latest


   
