---
- name: Patching of RHEL systems
  connection: ssh
  hosts: all
  gather_facts: yes
  become: true
  become_method: sudo
  
  tasks:
    - name: Check if RHEL system
      yum:
        name: vim
        state: latest
      debug:
        var=hostvars[inventory_hostname].ansible_distribution
 # when: hostvars[inventory_hostname].ansible_distribution == "  
   
   
