---
- name: Patching of RHEL systems
  hosts: localhost
  tasks:
    - name: add host to "selectIP" group
      add_host:
        groups: selectIP
        name: "{{ host_ip }}"
        
- hosts: selectIP
  connection: ssh
  gather_facts: yes
  become: true
  become_method: sudo
  
  tasks:    
    - name:
      fail:
        msg: "Virtual Machine does not have RHEL OS"
      when: var=hostvars[inventory_hostname].ansible_distribution == "CentOS"
    - name: update the packages
      yum:
        name: '*'
        state: latest
      
       
     
#   tasks:
#     - name: Check if RHEL system
#       yum:
#         name: vim
#         state: latest
#       debug:
#         var=hostvars[inventory_hostname].ansible_distribution
 # when: hostvars[inventory_hostname].ansible_distribution == "  
   
   
