---
- name: Patching of RHEL systems
  hosts: guests
  connection: ssh
  gather_facts: yes
  become: true
  become_method: sudo
  
  tasks:
    - name: print ips 
      shell:
        cmd: ip a
     
#   tasks:
#     - name: Check if RHEL system
#       yum:
#         name: vim
#         state: latest
#       debug:
#         var=hostvars[inventory_hostname].ansible_distribution
 # when: hostvars[inventory_hostname].ansible_distribution == "  
   
   
