---
- name: RedHat Subscription Management of RHEL systems
  hosts: localhost
  tasks:
    - name: add host to selectIP group
      add_host:
        groups: selectIP
        name: "{{ host_ip }}"
    - debug:
        msg: "Host IP: {{ host_ip }}"
        
- hosts: selectIP
  connection: ssh
  gather_facts: yes
  become: true
  become_method: sudo
  
  tasks:    
    - name: Check  if VM is RHEL machine
      fail:
        msg: "Virtual Machine does not have RHEL OS"
      when: hostvars[inventory_hostname]['ansible_distribution'] != "RedHat"
    - name: Install RHSM and Insights
      yum:
      name: '{{ item }}'
      state: present
      with_items:
      - redhat-access-insights
      - subscription-manager
    - name: Subscribing to pool-id
      redhat_subscription:
        state: present
        username: '{{ rhsm_username }}'
        password: '{{ rhsm_password }}'
        pool_ids: id
    - name: Enable all Repositories
      rhsm_repository:
        name: '*'
        state: enabled

    


   
