---
- hosts: localhost
  gather_facts: false
  vars:
    vcenter_server: 192.168.1.182
    vcenter_user: administrator
    vcenter_pass: Redhat@123
    vcenter_cluster: Datacenter1
    #final_delete:
  vars_files:
    - /tmp/vm_name_vars.yml
  tasks:
    - debug: var=vm_name

    - name: deleting vm
      debug:
        msg: "Deleting {{ vm_name }}"

    - name: Remove "{{ vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        #cluster: "{{ vcenter_cluster }}"
        name: "{{ item }}"
        state: absent
      register: vm_deletion_output
      loop: "{{ vm_name }}"
      when: vm_name is defined and final_delete is defined

    #- debug:
    #    msg: "{{ vm_deletion_output | default(omit) }}"

    - debug:
        msg: "VMs deleted successfully"
      when: vm_deletion_output.changed == true

    - debug:
        msg: "VMs deletion failed"
      when: vm_deletion_output.changed == false
