---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove "{{ vm_names }}"
      vmware_guest:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: no
        name: "{{ item | trim }}"
        state: absent
      register: vm_deletion_output
      loop: "{{ vm_name }}"
      when: vm_name is defined
      delegate_to: localhost

    - debug:
        msg: "VMs deleted successfully"
      when: vm_deletion_output.changed == true

    - debug:
        msg: "VMs deletion failed"
      when: vm_deletion_output.changed == false
