---
- hosts: localhost
  gather_facts: true
  become: yes
  vars:
    project_path: "{{ lookup('env', 'PWD') }}"
  tasks:
    - debug: var=ansible_hostname
    - debug:
        var: project_path
    - name: Collecting all poweredoff VM Names
      shell:  "{{project_path}}/vm_cli.ps1 -vcenter_server {{ lookup('env', 'VMWARE_HOST') }} -vcenter_user {{ lookup('env', 'VMWARE_USER') }} -vcenter_password {{ lookup('env', 'VMWARE_PASSWORD') }}"
      args:
        executable: /usr/bin/pwsh
      no_log: True
      register: vmnames
    - debug: var=vmnames
    - set_fact:
        vm_list: "{{ vmnames.stdout_lines }}"
    - debug: var=vm_list
#     - name: Generating Template for survey
#       template:
#         src: vm_name_vars.j2
#         dest: /tmp/vm_name_vars.yml

#     - name: copy vars file on all tower nodes
#       copy:
#         src: /tmp/vm_name_vars.yml
#         dest: /tmp/vm_name_vars.yml
#       delegate_to: 192.168.1.201

#     - name: copy vars file on all tower nodes
#       copy:
#         src: /tmp/vm_name_vars.yml
#         dest: /tmp/vm_name_vars.yml
#       delegate_to: 192.168.1.202
    
#     - name: copy vars file on all tower nodes
#       copy:
#         src: /tmp/vm_name_vars.yml
#         dest: /tmp/vm_name_vars.yml
#       delegate_to: 192.168.1.203


        #- name: adding all towernodes in temp host group
        #add_host:
        #group: towernodes
        #name: "{{ item }}"
        #loop: "{{ tower_nodes }}"

      #- hosts: towernodes
      #gather_facts: false
      #tasks:      
      #- name: copy vars file on all tower nodes
      #copy:
      #  src: /tmp/vm_name_vars.yml
      #  dest: /tmp/vm_name_vars.yml


