- hosts: "{{ zimbra_server_ip }}"
  roles:
     - role: zimbraserver
       hostname: "{{ansible_hostname}}"
       domain: "{{zimbra_domain}}"
       zmpasswd: "redhat"
       zmnetwork: "192.168.1.0/24"
