---
#
# Update packages
###############################################################################
- name: Install the default packages for CentOS/RedHat System
  yum:
    name: epel-release
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install the default packages for CentOS/RedHat System
  yum:
    name: "{{ centos_repo }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Updating all the packages for CentOS/RedHat System
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install the default packages for the playbook
  package:
    name: "{{ multidist }}"
    state: latest

#
# Hostname and Network
################################################################################
- name: Changing the hostname
  hostname:
    name: '{{ hostname }}.{{ domain }}'

- name: Including the hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ hostname }}.{{ domain }} {{ hostname }}'
    state: present


- name: Including the hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ zimbra_server_ip }} {{ hostname }}.{{ domain }} {{ hostname }}'
    state: present

